name: GitHub Actions Demo
run-name: ${{ github.actor }} is doing acceptance tests 🚀
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4

      - name: Test the Board is Empty on Start
        run: |
          python -m unittest minesweeper/tests/acceptanceTests/EmptyBoardOnStartTest.py